### ISSUE TITLE
Review: MyDataChart.jsx

### ISSUE THREAD

**Issue by sophiaelizecruz** [hot-n-code/ghg-tracker#100]
## Overview

Please review MyDataChart.jsx, which is a pie chart for the user page that should display the number of miles for each mode of alternative transportation for a specific user.

## Review Branch

* review-4

## Files to review

* [MyDataChart.jsx](https://github.com/hot-n-code/ghg-tracker/blob/issue-96/app/imports/ui/components/MyDataChart.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

4/30/2021 (Tuesday)

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by dmestacio** [comment]
The entire code was clean and very easy to read. Found no issue with it. Great job!

**Comment by annacampainha** [comment]
I found no issues.

**Comment by micgainey** [comment]
The code was very easy to read, I couldn't find any issues.

**Comment by timothyhuo1** [comment]
Code was easy to read
Line 8: ES-LINT-01

**Comment by vrabang** [comment]
Found no issues

**Comment by chakhon** [comment]
No issues found

**Comment by yiwenc22** [comment]
No issues found and code was easy to read.

**Comment by jackiewong99** [comment]
Overall, the code was easy to read. No issues found.

**Comment by cammoore** [comment]
MyDataChart.jsx

L11 Object deconstruction.
L12, 14, 16, 18, 20, 22, 25 Create an object with keys for these strings. 
L45-49: Use const 

Create a shared object with keys, backgroundColor, label?
