### ISSUE TITLE
Review: AltVehicleCard.jsx

### ISSUE THREAD

**Issue by sophiaelizecruz** [hot-n-code/ghg-tracker#135]
## Overview

Review the Alternative Transportation Card widget, which should allow the user to click through cards each displaying their GHG information for different modes of transportation.

## Review Branch

review-5

## Files to review

* [AltVehicleCard.jsx](https://github.com/hot-n-code/ghg-tracker/blob/master/app/imports/ui/components/user-page/AltVehicleCard.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

4/13/2021 (Tuesday)

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by dmestacio** [comment]
JS-08: Use JSDoc comments appropriately.
Lines 6, 9, 14, 25, 27, 32, 34, 67 should be //, not /**

Combine lines 28 and 29 in an object instead of using two arrays

Other than that, code was easy to read. Great job!

**Comment by sophiaelizecruz** [comment]
Design-05: Ensure comments are appropriate.
JS-08: Use JSDoc comments appropriately.

Other than that, the code was understandable.

**Comment by timothyhuo1** [comment]
JS-08: Use JSDoc comments appropriately.
Could create a shared object for L28, L29

**Comment by vrabang** [comment]
JS-08: Use JSDoc comments appropriately.
Other than that code was neat and understandable

**Comment by jackiewong99** [comment]
**JS-08**: Use JSDoc comments appropriately.

**L15**: Could rename "nextState" to a name like "buttonClickHandler".

**Reference L33**: Could convert component to be a function instead of a class, and use the "useState()" hook, that way you don't have to pass the value to the "render" method.

**Comment by cammoore** [comment]
## AltVehicleCard.jsx

JS-08 L9, 25, 27 32 etc use // instead of /**

L28 should we put this somewhere that other pages/components can use?
L33 is this a good variable name? Should it be a const?

**Comment by micgainey** [comment]
Design-05: Ensure comments are appropriate.
JS-08: Use JSDoc comments appropriately.
