### ISSUE TITLE
Review: AdminProfileList.jsx

### ISSUE THREAD

**Issue by sophiaelizecruz** [hot-n-code/ghg-tracker#159]
## Overview

Review the user list page for the admin side that displays all of the application's users and their profile information (email, goal, profile picture). Admins may find a certain user with the search component and checkboxes to hide/show certain columns of the table.

## Review Branch

review-6

## Files to review

* [AdminProfileList.jsx](https://github.com/hot-n-code/ghg-tracker/blob/master/app/imports/ui/pages/admin/AdminProfileList.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

4/27/2021 (Tuesday)

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by timothyhuo1** [comment]
JS-08: replace /** with //

**Comment by sophiaelizecruz** [comment]
JS-08: Use JSDoc comments appropriately.
Lines 10, 21: Use //

**Comment by jackiewong99** [comment]
Line 10, 21: Use // for comments instead of /** .

**Comment by vrabang** [comment]
JS-08: use // for comments

**Comment by annacampainha** [comment]
Design-09: Some functions could be added to utilities to use in other react tables
JS-08: use //

**Comment by micgainey** [comment]
JS-08: Use JSDoc comments appropriately.

**Comment by dmestacio** [comment]
JS-08:Lines 10, 21: Use // instead of /**

Lines 61, 63: div unnecessary
Lines 78-86: Use of Table component is unnecessary. Use Header instead.

**Comment by cammoore** [comment]
## AdminProfileList.jsx

JS-08 Use // instead of /** L21

L42 - 47 Does this change anything?

**Comment by yiwenc22** [comment]
JS-08 Use // instead of /** L21
