### ISSUE TITLE
Review: imports/ui/pages/CumulativePage.jsx

### ISSUE THREAD

**Issue by chakhon** [hot-n-code/ghg-tracker#19]
## Overview

Review the Landing Page

## Review Branch

review-1

## Files to review

* [CumulativePage.jsx](../tree/issue-18/app/imports/ui/pages/CumulativePage.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

2/9/2021 Tuesday

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by annacampainha** [comment]
Design: 
L8: rename the div class name ‘background’ as it is too broad. May cause confusion on the CSS since there are multiple backgrounds

**Comment by jackiewong99** [comment]
**Design-01**: Different modes of transportation section could be refactored to separate card components like "Transportation" or "TransportationCard".

**REACT-09**: Prefer functions vs. classes for stateless components.

**Comment by micgainey** [comment]
React-09 Prefer functions vs. classes for stateless components.

**Comment by timothyhuo1** [comment]
L4: Design-05: Comment is unnecessary or needs to be changed
L5: REACT-09: Prefer functions vs. classes

**Comment by dmestacio** [comment]
Not much issue here, just one thing I noticed: Some 'Header' components are one-liners while others are split into three lines.

**Comment by vrabang** [comment]
Design-05 L4: Comment is unnecessary

**Comment by sophiaelizecruz** [comment]
React-09 Prefer functions vs. classes for stateless components.

Also, renaming the file name from Cumulative to something more specific.

**Comment by cammoore** [comment]
React-09: L5, using class.
JS-05: L5-7, use arrow function to simplify.
