### ISSUE TITLE
Review: AddDailyData.jsx

### ISSUE THREAD

**Issue by dmestacio** [hot-n-code/ghg-tracker#71]
## Overview

Review the AddDailyData component (modal)

## Review Branch

review-2

## Files to review

* [AddDailyData.jsx](../tree/master/app/imports/ui/components/AddDailyData.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

03/02/2021 Tuesday

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by annacampainha** [comment]
I did not find any errors in this code. Very uniform and easy to read. ES Lint runs without errors as well.

**Comment by yiwenc22** [comment]
Most of the code is uniform and easy to read but it got some ES Lint Warning not error.
line 60 ESLINT -01 "promise returned from swal is ignored"
line 65 ESLINT -01 "should not disable eslint for no def and define it".

**Comment by sophiaelizecruz** [comment]
ESLINT-01: No errors, avoid warnings.
- Promise returned from swal is ignored
- Other than that, could not find other errors with the code. Able to understand.

**Comment by vrabang** [comment]
Found no errors and code is easy to read

**Comment by timothyhuo1** [comment]
Code was easy to read, could use arrow functions

**Comment by jackiewong99** [comment]
**JS-01:**
Line 79: Variable name **fRef** could be renamed to **formRef**.

**JS-06:** 
Line 48 & 49: Can use built-in JavaScript **Math.max()** and **Array.find()** functions.

**Comment by micgainey** [comment]
line 58 METEOR-04: use validated methods to update collections.
DailyUserData.collection.insert should eventually be DailyUserData.collection.define

**Comment by cammoore** [comment]
AddDailyData.jsx

React-07: L40 Should be in the withTracker and passed in as props.

Design-09: L46 probably want to make this an exported function that
takes in 3 parameters, milesTraveled, modeOfTransportation, mpg. Then
we can use this in other places.

JS-08: L14, 25, 39, 45, 53, 72, 77, 106, 111 Use //.

**Comment by chakhon** [comment]
Line 60 ESLINT-01: Promise returned from swal is ignored
Line 65 ESLINT-01: Eslint-disable-next-line no-undef
Could use some more description on function parameter
