### ISSUE TITLE
Review: ProfileCard.jsx

### ISSUE THREAD

**Issue by sophiaelizecruz** [hot-n-code/ghg-tracker#76]
## Overview

Please review the ProfileCard component, which should display the user's profile picture, name, email, GHG reduction goal, and an edit profile button.

## Review Branch

review-3

## Files to review

* [ProfileCard.jsx](https://github.com/hot-n-code/ghg-tracker/blob/issue-69/app/imports/ui/components/ProfileCard.jsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Special requests for this review

Is the user data in the card enough? Anything that should be added? Taken out? Style-wise, any improvements?

## Due date

3/9/2021 (Tuesday)

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by yiwenc22** [comment]
I think the user data in the card is enough to keep it simple unless someone think we need more info. Otherwise the code is simple, easy to read, and well organize.

**Comment by micgainey** [comment]
REACT-09 Prefer functions vs. classes for stateless components. Other than that very easy to read and understand

**Comment by dmestacio** [comment]
REACT-09: Prefer functions over classes. 

Line 26: 'Edit Profile' should be inside <Link> </Link> (unless this is temporary?)

Other than that, code is very easy to read. Thank you!

**Comment by jackiewong99** [comment]
**REACT-09:** Prefer functions over classes for stateless components.

Overall, the code was easy to read and nicely written.

**Comment by vrabang** [comment]
REACT-09: Prefer functions over classes for stateless components. 
But other than that code is clean and easy to read.

**Comment by annacampainha** [comment]
**REACT-09** Prefer functions vs. classes for stateless components

**Comment by timothyhuo1** [comment]
L7: REACT-09: Prefer functions for stateless components

**Comment by cammoore** [comment]
Lots of code for a single review.

UserProfile.jsx

JS-08 comments

REACT-09 L27 prefer functions.

REACT-06: L51 use withTracker for collection access.
L49, L53 could be consts passed in via withTracker

UserInfo.js

UserTransportation.js

JS L16 Might want to export this array so we can use it in other
places like the UI.

UserVehicles.js

JS-08 comments

JS L19-66 might want to export this array so we can use it in other
places. Similar comment on L72

**Comment by cammoore** [comment]
ProfileCard.jsx

REACT-09 L7 prefer function.

JS-08 L6, 34, 39. Use // for the comments.

REACT L36 might want to define the object properties

  profile: PropTypes.shape({
    image: PropTypes.string,
    name: PropTypes.string,
    email: PropTypes.string,
    _id: PropTypes.string,
  }).isRequired,
